services:
  - type: web
    name: movie-theater-booking
    env: python
    rootDir: homework2
    plan: free
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn movie_theater_booking.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString

databases:
  - name: movie-db
    plan: free
